### ISSUE TITLE
Improve documentation about requried extensions 

### ISSUE THREAD

**Issue by t-zuehlsdorff** [tembo-io/pg_timeseries#21]
Aloha,

i want to port your extension to the FreeBSD ports-tree so FreeBSD user can install the extension just by using the package manager.

When reading your documentation i spotted this part after creating the extension:
```
NOTICE:  installing required extension "columnar"
NOTICE:  installing required extension "pg_cron"
NOTICE:  installing required extension "pg_partman"
```

So i guess other extensions must already be installed to work?

Can you link them explicitly so i can port them too? pg_partman is already ported, but i can't find the columnar one.

**Comment by ChuckHend** [comment]
Hi @t-zuehlsdorff, the dependencies are somewhat complicated. We will improve on the installation story over time, but in the short term I think following the [dockerfile](https://github.com/tembo-io/pg_timeseries/blob/main/timeseries-pg/Dockerfile) build should show you how these extensions are compiled and installed, including `columnar`.

**Comment by jasonmp85** [comment]
Hey @t-zuehlsdorff, I'll add links for the other extensions into the README.

**Comment by t-zuehlsdorff** [comment]
This is great, thank you very much! :)  Now i can start my quest to port this to FreeBSD :)
/close
