### ISSUE TITLE
Missing `pg_ivm` extension in v0.1.6/latest Docker tag

### ISSUE THREAD

**Issue by kaysersoze** [tembo-io/pg_timeseries#33]
When creating a new `pg_timeseries` project using the `latest` tag, and executing the `CREATE EXTENSION timeseries CASCADE;` instruction, I get the following Postgres error:

```log
NOTICE:  installing required extension "columnar"
NOTICE:  installing required extension "pg_cron"
NOTICE:  installing required extension "pg_ivm"

Query 1 ERROR at Line 1: : ERROR:  extension "pg_ivm" is not available
DETAIL:  Could not open extension control file "/usr/share/postgresql/16/extension/pg_ivm.control": No such file or directory.
HINT:  The extension must first be installed on the system where PostgreSQL is running.
```

However, if I revert to the v0.1.5 Docker tag, it works correctly:

```log
NOTICE:  installing required extension "columnar"
NOTICE:  installing required extension "pg_cron"
NOTICE:  installing required extension "pg_partman"

Query 1 OK: CREATE EXTENSION
```

**Comment by ChuckHend** [comment]
Thanks for raising the issue @kaysersoze . We added a dependency on pg_ivm (Tembo's fork of it) in the latest release. This was an oversight on our part that it didnt make it into the image.

We'll get the build updated and a new image published.

**Comment by ChuckHend** [comment]
@kaysersoze thanks again for letting us know about the issue. We rebuilt the latest and v0.1.6 tags
